# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-24 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=10000)),
                ('data', models.DateTimeField(blank=True, help_text=b'formato YYYY-MM-DDThh:mm:ss', null=True)),
                ('prezzo', models.FloatField(max_length=5)),
                ('sconto', models.FloatField(blank=True, max_length=2)),
                ('facilitazioni', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': "Attivita'",
            },
        ),
        migrations.CreateModel(
            name='Risultato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risultato', models.CharField(blank=True, max_length=10000)),
                ('classifica', models.CharField(blank=True, max_length=10000)),
                ('note', models.CharField(blank=True, max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attivita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sito.Attivita')),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'Risultati',
            },
        ),
        migrations.CreateModel(
            name='Sportivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
                ('sport', models.CharField(max_length=20)),
                ('data_nascita', models.DateField(blank=True, default=b'01/01/1900')),
                ('luogo_nascita', models.CharField(blank=True, default=b'', max_length=100)),
                ('paese_nascita', models.CharField(blank=True, default=b'', max_length=100)),
                ('altezza', models.FloatField(blank=True, max_length=3)),
                ('peso', models.FloatField(blank=True, max_length=3)),
                ('foto', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, related_name='sportivi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'verbose_name_plural': 'Sportivi',
            },
        ),
        migrations.AddField(
            model_name='risultato',
            name='vincitore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sito.Sportivo'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='organizzatore',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, to='sito.Sportivo'),
        ),
        migrations.AddField(
            model_name='attivita',
            name='owner',
            field=models.ForeignKey(default=b'0', on_delete=django.db.models.deletion.CASCADE, related_name='attivita', to=settings.AUTH_USER_MODEL),
        ),
    ]
